[project]
name = "atmosphere.common"
version = "0.5.0"
dependencies = [
    "ansible-core>=2.18.4",
    "docker-image-py>=0.1.13",
    "kubernetes>=33.1.0",
]

[dependency-groups]
dev = [
    "molecule>=25.9.0.rc1",
]
