# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

# Version of Ironic Standalone Operator to install
baremetal_operator_version: 0.9.0

# Git repository location for Baremetal Operator
baremetal_operator_git_url: https://github.com/metal3-io/baremetal-operator

# Git reference for Baremetal Operator
baremetal_operator_git_ref:
  tag: "v{{ baremetal_operator_version }}"

# Namespace to install Ironic Standalone Operator
baremetal_operator_namespace: baremetal-operator-system
