# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

dellhw_exporter_helm_repository_name: prometheus-dellhw-exporter
dellhw_exporter_helm_repository_url: https://galexrt.github.io/dellhw_exporter
dellhw_exporter_helm_chart_name: prometheus-dellhw-exporter
dellhw_exporter_helm_chart_version: 1.0.3

dellhw_exporter_helm_release_namespace: monitoring
dellhw_exporter_helm_release_name: prometheus-dellhw-exporter

dellhw_exporter_helm_values: {}

dellhw_exporter_image: quay.io/galexrt/dellhw_exporter:v2.0.0-rc.1
