# Copyright (c) 2026 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy "secretgen-controller"
  hosts: "{{ target | default('all') }}"
  become: true
  gather_facts: false
  roles:
    - role: atmosphere.common.secretgen_controller
      tags:
        - secretgen-controller
